/*
  What the linter is here for, given `astro check` already runs.

  The type checker answers "does this compile". It has nothing to say about a
  promise nobody awaited, a hook called conditionally, or a `catch` that
  swallows the error — the three things that have actually gone wrong in this
  codebase. Every rule turned on below is one of those: a mistake that type
  checks, passes review, and shows up as a reminder that silently did not post.

  Stylistic rules are all off. Prettier settles formatting, and a linter that
  also has opinions about it just produces two tools disagreeing in CI.
*/

import js from "@eslint/js";
import tseslint from "typescript-eslint";
import astro from "eslint-plugin-astro";
import reactHooks from "eslint-plugin-react-hooks";
import prettier from "eslint-config-prettier";
import globals from "globals";

export default tseslint.config(
  {
    /*
      generated or vendored, and not ours to fix. `src/components/ui` is shadcn
      output — it is re-generated by the CLI, so a lint fix there is lost the
      next time somebody adds a component
    */
    ignores: [
      "dist/",
      ".astro/",
      ".wrangler/",
      "node_modules/",
      "worker-configuration.d.ts",
      "src/components/ui/**",
    ],
  },

  js.configs.recommended,

  /*
    the type-aware preset rather than the plain one. it is the whole reason to
    run a linter here — `no-floating-promises` and `no-misused-promises` cannot
    be decided without types, and they are the rules that catch a reminder
    quietly failing to send.

    scoped to .ts/.tsx on purpose: see the .astro block below
  */
  ...tseslint.configs.recommendedTypeChecked.map((config) => ({
    ...config,
    files: ["**/*.{ts,tsx}"],
  })),

  {
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },

  ...astro.configs.recommended,

  {
    /*
      .astro files are linted without types.

      astro-eslint-parser builds its own AST for the frontmatter and does not
      implement `projectService`, and the type-aware rules walk into nodes it
      leaves without parents — `no-misused-promises` crashes outright on an
      `await` in the frontmatter of an admin page. The syntactic rules still
      apply, and `astro check` already type checks these files properly, so
      what is lost here is covered a step away
    */
    files: ["**/*.astro"],
    extends: [tseslint.configs.disableTypeChecked],
  },

  {
    files: ["**/*.{ts,tsx}"],
    plugins: { "react-hooks": reactHooks },
    rules: {
      ...reactHooks.configs.recommended.rules,

      /*
        an unawaited promise in a worker is the specific way this codebase
        breaks: the request returns 200, the isolate is torn down, and the
        Discord post never happens. `waitUntil` is the deliberate form and is
        still allowed
      */
      "@typescript-eslint/no-floating-promises": "error",

      /*
        off, and not close.

        ESLint's program does not resolve the same lib as `astro check` — the
        Workers types are not in it, so `response.json()` reads as `any` there
        and every `as { ... }` on one looks redundant. Its autofix deleted 37 of
        them and left a tree that does not compile. A rule that cannot see the
        types the compiler sees has no business editing assertions about them
      */
      "@typescript-eslint/no-unnecessary-type-assertion": "off",

      /* an underscore is how you say "deliberately unused" */
      "@typescript-eslint/no-unused-vars": [
        "error",
        {
          argsIgnorePattern: "^_",
          varsIgnorePattern: "^_",
          caughtErrorsIgnorePattern: "^_",
        },
      ],

      /*
        `catch {}` is a decision. it is the right one in several places here —
        an unparseable cookie is not an error, it is a signed-out visitor — but
        it should be visible, so an empty block needs a comment saying so
      */
      "no-empty": ["error", { allowEmptyCatch: false }],
    },
  },

  {
    /* the worker and the config run in node or workerd, not a browser */
    files: ["src/worker.ts", "*.config.{js,mjs,ts}", "drizzle.config.ts"],
    languageOptions: { globals: globals.node },
  },

  {
    /*
      ambient declarations are shaped by what they are declaring, not by taste.
      Astro requires the triple-slash references, and `interface Env extends
      HareWareEnv {}` exists precisely to give one shape two names — the empty
      body is the point
    */
    files: ["**/*.d.ts"],
    rules: {
      "@typescript-eslint/triple-slash-reference": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "@typescript-eslint/no-unused-vars": "off",
    },
  },

  {
    files: ["**/*.{test,spec}.{ts,tsx}", "vitest*.config.ts"],
    rules: {
      /*
        a fetch mock is `async () => new Response(...)`: async because that is
        the signature it stands in for, with nothing to await because there is
        no i/o. requiring an await would mean writing a worse fake
      */
      "@typescript-eslint/require-await": "off",

      /*
        a test asserts on shapes it just built. narrowing every mock response
        would obscure what is being tested and protect nothing
      */
      "@typescript-eslint/no-unsafe-assignment": "off",
      "@typescript-eslint/no-unsafe-member-access": "off",
      "@typescript-eslint/no-unsafe-argument": "off",
      "@typescript-eslint/no-unsafe-return": "off",
      "@typescript-eslint/no-unsafe-call": "off",
    },
  },

  /* last, so it switches off everything Prettier already decides */
  prettier,
);
